### ISSUE TITLE
Needs updated verbiage to state valid URL endpoints.

### ISSUE THREAD

**Issue by Zsoldier** [Azure/Microsoft.AVS.Management#178]
Meaning, does the URL need to be publicly accessible? Does it need to be an http(s) url endpoint?
@gungazoo 

https://github.com/Azure/Microsoft.AVS.Management/blob/dc14cb254c0bd83b60bb3ef6898e8ee3dcb9aeda/Microsoft.AVS.Management/Microsoft.AVS.Management.psm1#L1585

**Comment by gungazoo** [comment]
It does need to be publicly accessible and will work with either HTTP or HTTPS.

**Comment by gungazoo** [comment]
@Zsoldier 

I didn't think to close this but on May 11th I changed:

The customer is responsible for putting the VMware Tools zip file in a downloadable location.

to

The customer is responsible for putting the VMware Tools zip file in a publicly available HTTP(S) downloadable location.

Did that achieve what you were looking for?
