### ISSUE TITLE
Multiple Datastores behavior?

### ISSUE THREAD

**Issue by Zsoldier** [Azure/Microsoft.AVS.Management#179]
If customer has an ANF or datastore other than just vSAN, how does this work?
HCX also creates a datastore, does this setup only on targeted datastore?
@gungazoo 

https://github.com/Azure/Microsoft.AVS.Management/blob/dc14cb254c0bd83b60bb3ef6898e8ee3dcb9aeda/Microsoft.AVS.Management/Microsoft.AVS.Management.psm1#L1591

**Comment by gungazoo** [comment]
It only looks for type "vsan" datastores.
